### PR TITLE
FEATURE: add a basic static website for GOATs

### PR DESCRIPTION
**Pull request by amtoine**
This PR adds a very simple set of `HTML` source files to deploy a super simple static website for GOATs with the list of all the projects of the organization.

You can try it out really quick with
```bash
gh pr checkout 1
{{BROWSER}} index.html
```
:ok_hand:

### CODE REVIEW

**Comment by dolphinau** [comment]
Mmm I need to change my remote to github.com/goatfiles before :thinking: 
How can I do this without breaking everything and loosing my `atxr` branch?

**Comment by amtoine** [comment]
> Mmm I need to change my remote to github.com/goatfiles before thinking How can I do this without breaking everything and loosing my `atxr` branch?
>
do you mean changing that in this repo? you won't loose anything :thinking:  
i'm not sure what you want to achieve here :confused: 
what is the output of `git remote -v`? :yum:

**Comment by dolphinau** [comment]
```bash
~ ❯ cfg remote -v
origin	git@github.com:atxr/dotfiles-1.git (fetch)
origin	git@github.com:atxr/dotfiles-1.git (push)
upstream	https://www.github.com/amtoine/dotfiles (fetch)
upstream	https://www.github.com/amtoine/dotfiles (push)
```
I just want to `gh pr checkout 1`

**Comment by amtoine** [comment]
> ```shell
> ~ ❯ cfg remote -v
> origin	git@github.com:atxr/dotfiles-1.git (fetch)
> origin	git@github.com:atxr/dotfiles-1.git (push)
> upstream	https://www.github.com/amtoine/dotfiles (fetch)
> upstream	https://www.github.com/amtoine/dotfiles (push)
> ```
> 
> I just want to `gh pr checkout 1`
>
**are you on the right repo?** :eyes:
`cfg` and "dotfiles" look suspicious to me :thinking: 

anyway, you can simply 
```shell
git fetch --all
git checkout ...
```
or maybe
```shell
gh pr checkout --repo https://github.com/goatfiles/dotfiles/pull/1
```
according to `gh pr --help` :+1:

**Comment by amtoine** [comment]
@atxr? :yum:

**Comment by dolphinau** [comment]
That's great! I like the design so far :wink: 
Let's deploy this :rocket:

**Review by dolphinau — APPROVED** [review]

**Comment by amtoine** [comment]
i'll deploy it then :+1:

**Pull request merged**
